### ISSUE TITLE
Issue with the model / user function

### ISSUE THREAD

**Issue by EchterAlsFake** [Egsagon/PHUB#18]
Hi, 

I got this error when using the User function:

```
Traceback (most recent call last):
  File "/home/asuna/PycharmProjects/Porn_Fetch/Porn_Fetch.py", line 492, in user_channel
    total_videos = user_object.videos
                   ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/asuna/PycharmProjects/Porn_Fetch/venv/lib/python3.11/site-packages/phub/objects/user.py", line 128, in videos
    return UQuery(client = self.client, args = url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Query.__init__() got an unexpected keyword argument 'args'
```

I tried it also with a simple test script:
```
from phub import Client

c = Client()
x = c.get_user("https://www.pornhub.com/model/sofia-simens")
videos = x.videos
```

I've tried with different models using newest commit from your master branch

**Comment by Egsagon** [comment]
Hey, thanks, it was just typos. I really need to make tests for this package because those happen to often.
