### ISSUE TITLE
Error accessing the Account feed

### ISSUE THREAD

**Issue by EchterAlsFake** [Egsagon/PHUB#28]
Hi, I am trying to access the Account feed. I am using the latest commits from your repository.
```
Traceback (most recent call last):
  File "C:\Users\habel\PycharmProjects\Porn_Fetch\tests.py", line 11, in <module>
    print(c.account.feed)
          ^^^^^^^^^^^^^^
  File "C:\Users\habel\AppData\Local\Programs\Python\Python312\Lib\functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\habel\PycharmProjects\Porn_Fetch\venv\Lib\site-packages\phub\objects\account.py", line 145, in feed
    from .query import Feed
ImportError: cannot import name 'Feed' from 'phub.objects.query' (C:\Users\habel\PycharmProjects\Porn_Fetch\venv\Lib\site-packages\phub\objects\query.py)

```

Here's the code segment I use:

```
c = Client(username, password, language="en", delay=False, login=False)
c.login()

print(c.account.feed.feed)
```

**Comment by Egsagon** [comment]
Hi,
This was probably due to a structure change in the query file. This should be solved now, thanks.
