### ISSUE TITLE
UnboundLocalError: cannot access local variable 'markers' where it is not associated with a value

### ISSUE THREAD

**Issue by EchterAlsFake** [Egsagon/PHUB#39]
Hi,

I tried accessing videos from a model but got this error:

```
200 https://www.pornhub.com/pornstar/alex-adams/videos
200 https://www.pornhub.com/pornstar/alex-adams/videos/upload
Traceback (most recent call last):
  File "/home/asuna/PycharmProjects/Porn_Fetch/tests.py", line 6, in <module>
    for video in videos:
  File "/home/asuna/PycharmProjects/Porn_Fetch/venv/lib/python3.11/site-packages/phub/objects/query.py", line 126, in __iter__
    for item in page:
  File "/home/asuna/PycharmProjects/Porn_Fetch/venv/lib/python3.11/site-packages/phub/objects/query.py", line 35, in Page
    wrapped = query._parse_item(item)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asuna/PycharmProjects/Porn_Fetch/venv/lib/python3.11/site-packages/phub/objects/query.py", line 303, in _parse_item
    markers = ' '.join(consts.re.get_markers(markers)).split()
                                             ^^^^^^^
UnboundLocalError: cannot access local variable 'markers' where it is not associated with a value
```

Using this code as a test:

```python
from phub import Client

c = Client()
user = c.get_user("https://de.pornhub.com/pornstar/alex-adams")
videos = user.videos
for video in videos:
    print(video.title)
```

**Comment by Egsagon** [comment]
Fixed, thanks!
