### ISSUE TITLE
ConnectionError: Request `{URL}` failed.

### ISSUE THREAD

**Issue by amiyoghoshstar** [Egsagon/PHUB#8]
Hi, 
I am getting this error while downloading the video. I used example code to test first
**Code :** 
```
import phub

client = phub.Client()
# 
video = client.get('https://www.pornhub.org/view_video.php?viewkey=6440f82ee3f4f')
print('Downloading:', video.title)

# Download on working dir with best quality
video.download('.', quality = phub.Quality.BEST)
```

**Error Response :** 
```
Traceback (most recent call last):
  File "D:\RandD\pornhub video downloader\test.py", line 5, in <module>
    video = client.get('https://www.pornhub.org/view_video.php?viewkey=6440f82ee3f4f')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\phub\core.py", line 329, in get
    return classes.Video(client = self, url = url, preload = preload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\phub\classes.py", line 185, in __init__
    self.refresh()
  File "C:\Python311\Lib\site-packages\phub\classes.py", line 203, in refresh
    response = self.client._call('GET', self.url)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\phub\core.py", line 265, in _call
    raise ConnectionError(f'Request `{func}` failed.')
ConnectionError: Request `https://www.pornhub.org/view_video.php?viewkey=6440f82ee3f4f` failed.
```
Do i need to use any proxy server?

**Comment by Egsagon** [comment]
Fixed with 8b20c3ad8e88fb9fb9dacbe3fafa3898e3c0df78. Thanks for reporting this!
